"""
INVARIANT - Phase 1: Core Gate Engine
======================================
Four-gate deterministic verification system.
Pure Python, zero external deps beyond hashlib.
Compatible with Bittensor Python SDK v10.

This module is the HEART of INVARIANT. Every miner receipt
passes through these four gates. Any gate failure = zero score.
No partial credit. No exceptions.

Designed to be imported by both miner.py and validator.py.
"""

import hashlib
import struct
import time
import json
from dataclasses import dataclass, asdict
from typing import Optional, Tuple
from enum import Enum


# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────

RECEIPT_VERSION = 1
RECEIPT_SIZE_BYTES = 136  # 32+32+32+8+32

# Gate failure codes — deterministic, shared between miner and validator
class GateResult(Enum):
    PASS               = "PASS"
    AGENT_NOT_AUTH     = "GATE1_AGENT_NOT_AUTHORIZED"
    MODEL_NOT_APPROVED = "GATE2_MODEL_NOT_APPROVED"
    REPLAY_DETECTED    = "GATE3_REPLAY_DETECTED"
    DIGEST_MISMATCH    = "GATE4_DIGEST_MISMATCH"


# ─────────────────────────────────────────────
# IDENTITY DERIVATION (SHA Layer — Layer 1)
# ─────────────────────────────────────────────

def derive_software_agent_id(hotkey_ss58: str, model_hash: bytes, registration_block: int) -> bytes:
    """
    Software miner identity binding.
    agent_id = SHA-256(hotkey_ss58 || model_hash || registration_block_bytes)
    
    This ID is immutable post-registration.
    Changing any input requires governance approval + new registration.
    
    Args:
        hotkey_ss58:        Bittensor ss58 hotkey address string
        model_hash:         SHA-256 of model weights/version (32 bytes)
        registration_block: Block number at time of registration (uint64)
    
    Returns:
        32-byte agent_id
    """
    h = hashlib.sha256()
    h.update(hotkey_ss58.encode("utf-8"))
    h.update(model_hash)
    h.update(struct.pack(">Q", registration_block))  # big-endian uint64
    return h.digest()


def derive_hardware_agent_id(efuse_mac: bytes, chip_model_byte: bytes) -> bytes:
    """
    DePIN / hardware miner identity binding (Keccak-256 compatible with SHA Layer).
    agent_id = Keccak-256(efuse_mac || chip_model_byte)
    
    For DePIN miners (Lium nodes, IoT hardware, GPU rigs with eFuse).
    Falls back to SHA-256 if pysha3 not available (testnet only).
    
    Args:
        efuse_mac:        Device unique eFuse/MAC identifier bytes
        chip_model_byte:  Chip model identifier bytes
    
    Returns:
        32-byte agent_id
    """
    try:
        import sha3  # pysha3
        k = sha3.keccak_256()
        k.update(efuse_mac)
        k.update(chip_model_byte)
        return k.digest()
    except ImportError:
        # Fallback: SHA-256 (testnet acceptable, NOT mainnet)
        print("[INVARIANT WARNING] pysha3 not found. Using SHA-256 fallback. Install pysha3 for mainnet.")
        h = hashlib.sha256()
        h.update(efuse_mac)
        h.update(chip_model_byte)
        return h.digest()


def hash_model(model_identifier: str) -> bytes:
    """
    Compute model hash from a string identifier (path, name, or version string).
    In production: hash actual model weights file.
    
    Returns:
        32-byte SHA-256 hash
    """
    return hashlib.sha256(model_identifier.encode("utf-8")).digest()


# ─────────────────────────────────────────────
# RECEIPT STRUCTURE (TON-SHA Layer — Layer 2)
# ─────────────────────────────────────────────

@dataclass
class InvariantReceipt:
    """
    136-byte execution receipt. Generated by miner, verified by validator.
    
    Fields:
        agent_id       (32 bytes): Bound identity from Layer 1
        model_hash     (32 bytes): SHA-256(model_weights + version)
        execution_hash (32 bytes): SHA-256(task_input || output || tempo_id || timestamp)
        counter        ( 8 bytes): Monotonic uint64, strictly increasing per agent_id
        digest         (32 bytes): SHA-256(all four fields packed, big-endian)
        
    Total: 136 bytes
    """
    agent_id:       bytes  # 32 bytes
    model_hash:     bytes  # 32 bytes
    execution_hash: bytes  # 32 bytes
    counter:        int    # uint64
    digest:         bytes  # 32 bytes
    
    # Metadata (not included in digest — informational only)
    version:        int = RECEIPT_VERSION
    timestamp:      float = 0.0
    tempo_id:       int = 0

    def to_bytes(self) -> bytes:
        """Serialize receipt to 136 bytes (digest fields only)."""
        return (
            self.agent_id
            + self.model_hash
            + self.execution_hash
            + struct.pack(">Q", self.counter)
            + self.digest
        )

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dict for Axon transport."""
        return {
            "version":        self.version,
            "agent_id":       self.agent_id.hex(),
            "model_hash":     self.model_hash.hex(),
            "execution_hash": self.execution_hash.hex(),
            "counter":        self.counter,
            "digest":         self.digest.hex(),
            "timestamp":      self.timestamp,
            "tempo_id":       self.tempo_id,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "InvariantReceipt":
        """Deserialize from dict (received over Axon)."""
        return cls(
            version        = d.get("version", RECEIPT_VERSION),
            agent_id       = bytes.fromhex(d["agent_id"]),
            model_hash     = bytes.fromhex(d["model_hash"]),
            execution_hash = bytes.fromhex(d["execution_hash"]),
            counter        = d["counter"],
            digest         = bytes.fromhex(d["digest"]),
            timestamp      = d.get("timestamp", 0.0),
            tempo_id       = d.get("tempo_id", 0),
        )


# ─────────────────────────────────────────────
# RECEIPT GENERATION (Miner-side)
# ─────────────────────────────────────────────

def compute_execution_hash(task_input: str, output: str, tempo_id: int, timestamp: float) -> bytes:
    """
    Compute execution hash binding input+output+tempo+time together.
    Cannot be forged without running the actual computation on the actual input.
    
    Args:
        task_input: The task given by the validator (string or JSON)
        output:     The miner's actual output
        tempo_id:   Current subnet tempo number
        timestamp:  Unix timestamp of execution
    
    Returns:
        32-byte SHA-256 hash
    """
    h = hashlib.sha256()
    h.update(task_input.encode("utf-8"))
    h.update(output.encode("utf-8"))
    h.update(struct.pack(">Q", tempo_id))
    h.update(struct.pack(">d", timestamp))  # big-endian double
    return h.digest()


def compute_receipt_digest(agent_id: bytes, model_hash: bytes,
                           execution_hash: bytes, counter: int) -> bytes:
    """
    Compute the tamper-evident digest over all four receipt fields.
    Gate 4 verifies this. If ANY field changes, digest fails.
    
    Returns:
        32-byte SHA-256 digest
    """
    h = hashlib.sha256()
    h.update(agent_id)
    h.update(model_hash)
    h.update(execution_hash)
    h.update(struct.pack(">Q", counter))
    return h.digest()


def generate_receipt(
    agent_id:   bytes,
    model_hash: bytes,
    task_input: str,
    output:     str,
    counter:    int,
    tempo_id:   int,
) -> InvariantReceipt:
    """
    Full receipt generation. Called by miner after task execution.
    
    Args:
        agent_id:   Miner's bound identity (from Layer 1)
        model_hash: SHA-256 of the exact model/code used
        task_input: Raw task input received from validator
        output:     Miner's computed output
        counter:    Current monotonic counter (miner maintains this state)
        tempo_id:   Current subnet tempo
    
    Returns:
        Fully-formed InvariantReceipt ready for submission
    """
    ts = time.time()
    execution_hash = compute_execution_hash(task_input, output, tempo_id, ts)
    digest = compute_receipt_digest(agent_id, model_hash, execution_hash, counter)
    
    return InvariantReceipt(
        agent_id       = agent_id,
        model_hash     = model_hash,
        execution_hash = execution_hash,
        counter        = counter,
        digest         = digest,
        timestamp      = ts,
        tempo_id       = tempo_id,
    )


# ─────────────────────────────────────────────
# FOUR-GATE VERIFICATION (Validator-side)
# ─────────────────────────────────────────────

class InvariantVerifier:
    """
    Stateful four-gate verifier. One instance per validator process.
    Maintains counter state across tempos (persistent via state file).
    
    Usage:
        verifier = InvariantVerifier(registry, state_path="./invariant_state.json")
        result, gate = verifier.verify(receipt)
        if result != GateResult.PASS:
            score = 0
    """
    
    def __init__(self, registry: "InvariantRegistry", state_path: str = "./invariant_state.json"):
        self.registry   = registry
        self.state_path = state_path
        self._counters  = self._load_counters()
    
    def _load_counters(self) -> dict:
        """Load persisted counter state from disk."""
        try:
            with open(self.state_path, "r") as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            return {}
    
    def _save_counters(self):
        """Persist counter state to disk after each tempo."""
        with open(self.state_path, "w") as f:
            json.dump(self._counters, f)
    
    def get_counter(self, agent_id_hex: str) -> int:
        """Get last confirmed counter for an agent."""
        return self._counters.get(agent_id_hex, 0)
    
    def advance_counter(self, agent_id_hex: str, new_counter: int):
        """Advance counter after successful Gate 3 pass."""
        self._counters[agent_id_hex] = new_counter
        self._save_counters()
    
    def verify(self, receipt: InvariantReceipt) -> Tuple[GateResult, Optional[str]]:
        """
        Run all four gates sequentially. Returns on first failure.
        
        Returns:
            (GateResult.PASS, None) on success
            (GateResult.FAIL_CODE, failure_detail) on any failure
        
        Time complexity: O(1) — all operations are hash comparisons
        Typical runtime: < 1ms per receipt on any modern CPU
        """
        agent_id_hex = receipt.agent_id.hex()
        
        # ── GATE 1: Identity Authorization ──────────────────────
        # Is this agent_id registered in the INVARIANT identity registry?
        if not self.registry.is_authorized(receipt.agent_id):
            return GateResult.AGENT_NOT_AUTH, f"agent_id={agent_id_hex[:16]}... not in registry"
        
        # ── GATE 2: Model Approval ───────────────────────────────
        # Is the declared model hash in the approved models list?
        if not self.registry.is_approved_model(receipt.model_hash):
            return GateResult.MODEL_NOT_APPROVED, f"model_hash={receipt.model_hash.hex()[:16]}... not approved"
        
        # ── GATE 3: Replay Protection ────────────────────────────
        # Counter must be strictly greater than the last confirmed counter.
        # Blocks exact replays and counter rollback attacks.
        last_counter = self.get_counter(agent_id_hex)
        if receipt.counter <= last_counter:
            return GateResult.REPLAY_DETECTED, (
                f"counter={receipt.counter} not > last_confirmed={last_counter}"
            )
        
        # ── GATE 4: Digest Integrity ─────────────────────────────
        # Recompute digest from the four fields. Must match submitted digest.
        # If ANY field was tampered with, this fails.
        expected_digest = compute_receipt_digest(
            receipt.agent_id,
            receipt.model_hash,
            receipt.execution_hash,
            receipt.counter,
        )
        if expected_digest != receipt.digest:
            return GateResult.DIGEST_MISMATCH, (
                f"expected={expected_digest.hex()[:16]}... "
                f"got={receipt.digest.hex()[:16]}..."
            )
        
        # ── ALL GATES PASSED ─────────────────────────────────────
        # Advance counter. This receipt cannot be replayed.
        self.advance_counter(agent_id_hex, receipt.counter)
        return GateResult.PASS, None
    
    def verify_batch(self, receipts: list) -> list:
        """
        Verify a batch of receipts. Returns list of (GateResult, detail) tuples.
        Used by validators processing all miners in a tempo.
        """
        return [self.verify(r) for r in receipts]


# ─────────────────────────────────────────────
# REGISTRY (Shared between Miner and Validator)
# ─────────────────────────────────────────────

class InvariantRegistry:
    """
    In-memory registry of authorized agents and approved models.
    
    In Phase 1: loaded from a JSON file (on-chain anchoring comes in Phase 2).
    In Phase 2: synced from Bittensor metagraph + subtensor extrinsics.
    
    Thread-safe for read operations (single-writer, multiple readers).
    """
    
    def __init__(self, registry_path: str = "./invariant_registry.json"):
        self.registry_path = registry_path
        self._data = self._load()
    
    def _load(self) -> dict:
        try:
            with open(self.registry_path, "r") as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            return {"agents": {}, "models": [], "version": 1}
    
    def _save(self):
        with open(self.registry_path, "w") as f:
            json.dump(self._data, f, indent=2)
    
    def is_authorized(self, agent_id: bytes) -> bool:
        """Gate 1 check: is this agent_id in the registry?"""
        return agent_id.hex() in self._data.get("agents", {})
    
    def is_approved_model(self, model_hash: bytes) -> bool:
        """Gate 2 check: is this model hash approved?"""
        return model_hash.hex() in self._data.get("models", [])
    
    def register_agent(self, agent_id: bytes, hotkey: str, metadata: dict = None):
        """Register a new agent. Called at miner registration time."""
        self._data.setdefault("agents", {})[agent_id.hex()] = {
            "hotkey":     hotkey,
            "registered": time.time(),
            "metadata":   metadata or {},
        }
        self._save()
    
    def approve_model(self, model_hash: bytes):
        """Add a model hash to the approved list."""
        models = self._data.setdefault("models", [])
        if model_hash.hex() not in models:
            models.append(model_hash.hex())
            self._save()
    
    def get_agent(self, agent_id: bytes) -> Optional[dict]:
        """Get agent metadata."""
        return self._data.get("agents", {}).get(agent_id.hex())
    
    def list_agents(self) -> list:
        """List all registered agent IDs."""
        return list(self._data.get("agents", {}).keys())


# ─────────────────────────────────────────────
# QUICK SELF-TEST
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("INVARIANT Phase 1 — Gate Engine Self-Test")
    print("=" * 60)
    
    # Setup
    registry = InvariantRegistry("/tmp/test_registry.json")
    verifier = InvariantVerifier(registry, "/tmp/test_state.json")
    
    # Create test agent
    model_hash = hash_model("invariant-test-model-v1")
    agent_id   = derive_software_agent_id("5FakeHotkeyXXXXXXXXXXXX", model_hash, 1000)
    
    registry.register_agent(agent_id, "5FakeHotkeyXXXXXXXXXXXX", {"type": "software"})
    registry.approve_model(model_hash)
    
    # ── Test 1: Valid receipt ────────────────────────────────────
    receipt = generate_receipt(
        agent_id   = agent_id,
        model_hash = model_hash,
        task_input = "What is 2+2?",
        output     = "4",
        counter    = 1,
        tempo_id   = 100,
    )
    result, detail = verifier.verify(receipt)
    assert result == GateResult.PASS, f"Expected PASS, got {result}: {detail}"
    print(f"✅ Test 1 PASS: Valid receipt verified correctly")
    
    # ── Test 2: Replay attack ────────────────────────────────────
    result, detail = verifier.verify(receipt)  # Same receipt again
    assert result == GateResult.REPLAY_DETECTED, f"Expected REPLAY, got {result}"
    print(f"✅ Test 2 PASS: Replay attack blocked — Gate 3 fired")
    
    # ── Test 3: Tampered digest ──────────────────────────────────
    tampered = InvariantReceipt(
        agent_id       = receipt.agent_id,
        model_hash     = receipt.model_hash,
        execution_hash = receipt.execution_hash,
        counter        = 2,
        digest         = bytes(32),  # all zeros — forged/empty digest
        tempo_id       = 100,
    )
    result, detail = verifier.verify(tampered)
    assert result == GateResult.DIGEST_MISMATCH, f"Expected DIGEST_MISMATCH, got {result}"
    print(f"✅ Test 3 PASS: Tampered digest blocked — Gate 4 fired")
    
    # ── Test 4: Unknown agent ────────────────────────────────────
    fake_agent_id = bytes(32)  # all zeros
    fake_receipt = generate_receipt(
        agent_id   = fake_agent_id,
        model_hash = model_hash,
        task_input = "test",
        output     = "test",
        counter    = 1,
        tempo_id   = 100,
    )
    result, detail = verifier.verify(fake_receipt)
    assert result == GateResult.AGENT_NOT_AUTH, f"Expected AGENT_NOT_AUTH, got {result}"
    print(f"✅ Test 4 PASS: Unknown agent blocked — Gate 1 fired")
    
    # ── Test 5: Unapproved model ─────────────────────────────────
    bad_model = hash_model("unapproved-model-v999")
    bad_agent_id = derive_software_agent_id("5FakeHotkeyXXXXXXXXXXXX", bad_model, 1001)
    registry.register_agent(bad_agent_id, "5FakeHotkeyXXXXXXXXXXXX")
    # Note: NOT adding bad_model to approved models
    bad_receipt = generate_receipt(
        agent_id   = bad_agent_id,
        model_hash = bad_model,
        task_input = "test",
        output     = "test",
        counter    = 1,
        tempo_id   = 100,
    )
    result, detail = verifier.verify(bad_receipt)
    assert result == GateResult.MODEL_NOT_APPROVED, f"Expected MODEL_NOT_APPROVED, got {result}"
    print(f"✅ Test 5 PASS: Unapproved model blocked — Gate 2 fired")
    
    print()
    print("All 5 gate tests passed. INVARIANT Phase 1 engine is operational.")
    print(f"Receipt size: {len(receipt.to_bytes())} bytes (target: 136)")
    print(f"Receipt dict: {json.dumps(receipt.to_dict(), indent=2)[:200]}...")
